---
collections:
- name: community.general
  version: 4.1.0
- name: ansible.posix
  version: 1.3.0
- name: community.docker

roles:
- name: ansible-role-tor
  src: https://github.com/AnarchoTechNYC/ansible-role-tor.git
  scm: git
- name: ansible-role-mariadb
  src: https://github.com/adfinis-sygroup/ansible-role-mariadb
  scm: git
- name: ansible-role-nvm
  src: https://github.com/morgangraphics/ansible-role-nvm
  scm: git
# - src: nginxinc.nginx
- name: ansible-role-nginx
  src: https://github.com/nginxinc/ansible-role-nginx.git
  scm: git
  version: 0.21.0
- src: geerlingguy.nodejs
- src: geerlingguy.nginx
- src: geerlingguy.pip
- src: geerlingguy.docker_arm

