---

# https://gist.github.com/alexbosworth/2c5e185aedbdac45a03655b709e255a3


- name: create lnd-channel s3 backup shell script
  become: yes
  copy:
    src: "get_status.sh"
    dest: "/usr/local/bin/get_status.sh"
    mode: "0755"

