---

- name: install jq package
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name=jq state=present update_cache=yes 


- name: install get_status script
  become: yes
  copy:
    src: "get_status.sh"
    dest: "/usr/local/bin/get_status.sh"
    mode: "0755"

