---

# - name: Dispaly uuid & store in variable
#   command: blkid -s UUID -o value {{ dev_data_drive }}
#   register: uuid_swap

# - name: Add the below lines
#   blockinfile:
#     path: /etc/fstab
#     state: present
#     block: |
#       UUID={{ uuid_swap.stdout }}   {{ mount_path_data_drive }} ext4 defaults,rw,nofail 0 0
- name: Mount up data drive by label
  mount:
    path: "{{ data_drive_mountpoint }}"
    src: LABEL={{ data_drive_label }}
    opts: defaults,rw,nofail
    fstype: ext4
    state: mounted


- name: install network-manager package
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name=network-manager state=present update_cache=yes 

- name: install network-manager-gnome package
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name=network-manager-gnome state=present update_cache=yes 

- name: Configure dhcpcd to ignore wlan0
  blockinfile:
    path: /etc/dhcpcd.conf
    state: present
    block: |
      denyinterfaces wlan0

# - name: Restart service dhcpcd
#   ansible.builtin.service:
#     name: dhcpcd
#     state: restarted

- name: Configure Network Manager to control wlan0 and assume dhcp duties
  blockinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    block: |
      [main]
      plugins=ifupdown,keyfile
      dhcp=internal

      [ifupdown]
      managed=true

# - name: Unconditionally reboot the machine with all defaults
#   reboot:
