---

- name: restart bitcoind
  become: yes
  systemd: service="bitcoind.service" state="restarted" daemon_reload="yes"

- name: restart machine
  become: yes
  systemd: service="bitcoind.service" state="restarted" daemon_reload="yes"
